POST http://localhost:8080/api/customers/register
Content-Type: application/json

{
  "firstName": "gfd",
  "lastName": "gfd",
  "email": "oiy@example.com",
  "password": "password123",
  "phoneNumber": 123456789,
  "address": "123 Main St"
}

### log in
POST http://localhost:8080/api/customers/login
Content-Type: application/json

{
  "email": "oiy@example.com",
  "password": "password123"
}